window.CAMX_TEXT = {
  ko: {
    coverKicker:'CAMX 2026 · 참가업체',eventKicker:'전시회',researchKicker:'업체 정보',dataKicker:'자료 안내',eventInfo:'전시회 정보',searchArea:'업체 검색',marketFilters:'대분류 필터',segmentFilters:'세부 필터',statusFilters:'구분 필터',
    brand:'업체 탐색',location:'미국 애틀랜타',officialSite:'CAMX 공식 사이트 ↗',cover:'전시회 업체 탐색',intro:'참가업체 · 전시 정보 · 회사 자료',eventDate:'전시 9월 22–24일',officialDirectory:'공식 출품업체 명단 ↗',database:'참가업체 데이터베이스',snapshot:'2026. 9. 19 기준 스냅샷',statAll:'2026 업체 항목',statPrior:'2025 참관 주요 업체',statMatch:'2026 재확인',statNote:'CAMX 등록 정보와 회사 사이트·발표 자료를 함께 확인했습니다. 근거가 부족한 항목은 ‘기타’에서 볼 수 있습니다.',searchPlaceholder:'업체명, 제품, 기술 검색',clear:'초기화',marketLabel:'대분류',segmentLabel:'세부',scopeLabel:'구분',all:'전체',prior:'2025 참관 주요 업체',current:'2026 참가',other:'기타',scopeNote:'회사 링크가 없고 독립 자료로 확인되지 않은 업체는 임의의 검색 결과를 연결하지 않았습니다. 해당 업체는 ‘기타’에서 확인할 수 있습니다.',selectHint:'업체를 선택하면 자세히 볼 수 있습니다',dataNotes:'자료 기준',noteCurrent:'CAMX 공식 업체 디렉터리에 등재된 경우입니다.',notePrior:'제공된 2025 참관 보고서에 기록된 주요 업체만 표시합니다.',otherInfo:'기타 · 정보 부족',noteOther:'회사 자료가 부족하거나 분야 근거가 분명하지 않은 업체입니다. 산업 분야를 추정하지 않았습니다.',footerStart:'CAMX 2026 전시회 업체 탐색 · 비공식 자료',footerDirectory:'CAMX 공식 명단',footerSources:'개별 회사 공개 자료',
    resultCount:n=>`검색 결과 ${n.toLocaleString('ko-KR')}곳`,noResults:'검색 결과가 없습니다. 필터나 검색어를 바꿔 보세요.',more:n=>`더 보기 · ${n}곳`,snapshotCount:n=>`${n}곳 교차 확인`,attending:'2026 참가',notListed:'2026 명단 미확인',priorBadge:'2025 참관 주요 업체',infoMissing:'정보 부족',viewDetails:'상세 보기',emptyTitle:'업체를 선택하세요',emptyCopy:'회사 정보와 확인된 출처를 볼 수 있습니다.',profileKicker:'CAMX 2026 · 업체 정보',closeDetail:'상세 닫기',noCompanyInfo:'확인 가능한 회사 소개 자료가 없습니다.',noBooth:'부스 정보 없음',priorText:'제공된 2025 참관 보고서에 주요 업체로 기록되어 있습니다.',companyIntro:'회사 소개',companySiteNote:'개별 회사 사이트의 공개 소개 문구 · 자동 번역',editorialNote:'회사 발표 자료를 바탕으로 한 요약 · 자동 번역',camxIntro:'CAMX 등록 소개',camxNote:'2026 공식 업체 디렉터리 등록 문구 · 자동 번역',camxCategories:'CAMX 등록 제품 분류',exhibit:'2026 등록 전시 정보',latest:'최근 발표 · 개발 방향',latestNote:'아래 회사 발표 자료 기준 · 자동 번역',dataStatus:'자료 상태',siteInsufficient:'회사 사이트의 설명 자료가 부족해 산업 분야를 확정하지 않았습니다.',fieldInsufficient:'회사 자료는 확인했으나 항공·우주·자동차·AI 또는 소재·공정·부품 분야를 명확히 연결하기 어렵습니다.',priorOnly:'2025 참관 보고서에서만 확인되었습니다. 2026 공식 명단에서는 같은 업체를 찾지 못했습니다.',verified:'CAMX 디렉터리와 개별 회사 자료 또는 발표를 함께 확인했습니다.',companySite:'회사 사이트',camxPage:'CAMX 2026 업체 정보',loadError:'데이터를 불러오지 못했습니다.',refresh:'페이지를 새로고침해 주세요.',translationUnavailable:'번역 자료가 준비되지 않았습니다.',
    labels:{'전체':'전체','항공·우주':'항공·우주','자동차':'자동차','AI':'AI','소재':'소재','공정':'공정','부품':'부품'}
  },
  en: {
    coverKicker:'CAMX 2026 · EXHIBITORS',eventKicker:'THE EVENT',researchKicker:'EXHIBITOR DATA',dataKicker:'DATA NOTES',eventInfo:'Exhibition information',searchArea:'Exhibitor search',marketFilters:'Market filters',segmentFilters:'Segment filters',statusFilters:'Status filters',
    brand:'Exhibitor Explorer',location:'Atlanta, USA',officialSite:'CAMX official site ↗',cover:'Exhibitor Explorer',intro:'Exhibitors · Exhibits · Company Sources',eventDate:'Exhibition Sep 22–24',officialDirectory:'Official exhibitor directory ↗',database:'Exhibitor database',snapshot:'Snapshot · Sep 19, 2026',statAll:'2026 exhibitor entries',statPrior:'Key companies visited in 2025',statMatch:'Confirmed again in 2026',statNote:'CAMX listings were checked against company websites and announcements. Entries with limited evidence appear under “Other”.',searchPlaceholder:'Search company, product, technology',clear:'Clear',marketLabel:'Sector',segmentLabel:'Segment',scopeLabel:'Status',all:'All',prior:'Key companies visited in 2025',current:'2026 exhibitor',other:'Other',scopeNote:'When no company link or independent source could be verified, we did not attach an unverified search result. Find those entries under “Other”.',selectHint:'Select a company for details',dataNotes:'About this data',noteCurrent:'Listed in the official CAMX exhibitor directory.',notePrior:'Shows only the key companies recorded in the supplied 2025 visit report.',otherInfo:'Other · Insufficient information',noteOther:'The company source or sector evidence is insufficient. No sector was inferred.',footerStart:'CAMX 2026 Exhibitor Explorer · Unofficial resource',footerDirectory:'CAMX directory',footerSources:'Public company sources',
    resultCount:n=>`${n.toLocaleString('en-US')} results`,noResults:'No results. Try another search or filter.',more:n=>`Show ${n} more`,snapshotCount:n=>`${n} cross-checked`,attending:'2026 exhibitor',notListed:'Not found in 2026 directory',priorBadge:'Key company visited in 2025',infoMissing:'Insufficient information',viewDetails:'View details',emptyTitle:'Select a company',emptyCopy:'Company information and verified sources appear here.',profileKicker:'CAMX 2026 · COMPANY PROFILE',closeDetail:'Close details',noCompanyInfo:'No company overview is available.',noBooth:'Booth unavailable',priorText:'This company is recorded among the key companies in the supplied 2025 visit report.',companyIntro:'Company overview',companySiteNote:'Public company description · machine translation',editorialNote:'Company announcement summary · machine translation',camxIntro:'CAMX listing overview',camxNote:'Official 2026 directory text · machine translation',camxCategories:'CAMX product categories',exhibit:'2026 listed exhibits',latest:'Recent announcement · direction',latestNote:'Based on the linked company source · machine translation',dataStatus:'Source status',siteInsufficient:'Company website information was insufficient to confirm a sector.',fieldInsufficient:'The company source was found, but there is insufficient evidence for an aerospace, automotive or AI sector and a materials, process or components segment.',priorOnly:'Only the 2025 visit report names this company. The company was not found in the 2026 directory.',verified:'The CAMX listing was checked against a company source or announcement.',companySite:'Company website',camxPage:'CAMX 2026 listing',loadError:'Could not load the data.',refresh:'Please refresh the page.',translationUnavailable:'Translation unavailable.',
    labels:{'전체':'All','항공·우주':'Aerospace','자동차':'Automotive','AI':'AI','소재':'Materials','공정':'Process','부품':'Components'}
  }
};
